 insert into role(id, name, description) values (1, 'INSERT_USER','Cadastrar usuário');
 insert into role(id, name, description) values (2, 'UPDATE_USER','Atualizar usuário');
 insert into role(id, name, description) values (3, 'DELETE_USER','Remover usuário');
 insert into role(id, name, description) values (4, 'LIST_USER','Listar usuários');
 insert into role(id, name, description) values (5, 'INSERT_PROFILE','Cadastrar perfil');
 insert into role(id, name, description) values (6, 'LIST_PROFILE','Listar perfis');
 insert into role(id, name, description) values (7, 'UPDATE_PROFILE','Atualizar perfil');
 insert into role(id, name, description) values (8, 'DELETE_PROFILE','Remover perfis');
 insert into role(id, name, description) values (9, 'INSERT_NODE', 'Cadastrar nós');
 insert into role(id, name, description) values (10, 'LIST_NODE', 'Listar nós');
 insert into role(id, name, description) values (11, 'UPDATE_NODE', 'Atualizar nós');
 insert into role(id, name, description) values (12, 'DELETE_NODE', 'Remover nós');
 insert into role(id, name, description) values (13, 'CLONE_NODE', 'Clonar nós');
 insert into role(id, name, description) values (14, 'SERVICE_NODE', 'Executar serviços de manipulação dos nós');
 insert into role(id, name, description) values (15, 'INSERT_FILEDIR', 'Cadastrar diretórios');
 insert into role(id, name, description) values (16, 'LIST_FILEDIR', 'Listar diretórios');
 insert into role(id, name, description) values (17, 'UPDATE_FILEDIR', 'Atualizar diretórios');
 insert into role(id, name, description) values (18, 'DELETE_FILEDIR', 'Remover diretórios');
 insert into role(id, name, description) values (19, 'INSERT_EXECFILE', 'Cadastrar serviços de manipulação');
 insert into role(id, name, description) values (20, 'LIST_EXECFILE', 'Listar serviços de manipulação');
 insert into role(id, name, description) values (21, 'UPDATE_EXECFILE', 'Atualizar serviços de manipulação');
 insert into role(id, name, description) values (22, 'DELETE_EXECFILE', 'Remover serviços de manipulação');
 insert into role(id, name, description) values (23, 'SERVICE_EXECFILE', 'Executar serviço de manipulação');
 insert into role(id, name, description) values (24, 'INSERT_CONFFILE', 'Cadastrar arquivos de configuração');
 insert into role(id, name, description) values (25, 'LIST_CONFFILE', 'Listar arquivos de configuração');
 insert into role(id, name, description) values (26, 'UPDATE_CONFFILE', 'Atualizar arquivos de configuração');
 insert into role(id, name, description) values (27, 'CONFIGURE_CONFFILE', 'Abrir para edição de arquivos de configuração');
 insert into role(id, name, description) values (28, 'DELETE_CONFFILE', 'Remover arquivos de configuração');
 insert into role(id, name, description) values (29, 'INSERT_CLUSTER', 'Cadastrar cluster');
 insert into role(id, name, description) values (30, 'LIST_CLUSTER', 'Listar cluster');
 insert into role(id, name, description) values (31, 'UPDATE_CLUSTER', 'Atualizar cluster');
 insert into role(id, name, description) values (32, 'DELETE_CLUSTER', 'Remover cluster');
 insert into role(id, name, description) values (33, 'SERVICE_CLUSTER', 'Executar serviços de manipulação do cluster');
 insert into role(id, name, description) values (34, 'NOTIFICATION_CLUSTER', 'Atualizar padrões de notificação do cluster');
 insert into role(id, name, description) values (35, 'CONFMONITOR_CLUSTER', 'Atualizar configurações de monitoramento do cluster');
 insert into role(id, name, description) values (36, 'MONITOR_CLUSTER','Monitorar informações do cluster');
 insert into role(id, name, description) values (37, 'MONITOR_NODE','Monitorar informações do nó');

 insert into profile(id, name) values(1, 'MASTER');
 insert into profile_role(profile_id, role_id) values(1,1);
 insert into profile_role(profile_id, role_id) values(1,2);
 insert into profile_role(profile_id, role_id) values(1,3);
 insert into profile_role(profile_id, role_id) values(1,4);
 insert into profile_role(profile_id, role_id) values(1,5);
 insert into profile_role(profile_id, role_id) values(1,6);
 insert into profile_role(profile_id, role_id) values(1,7);
 insert into profile_role(profile_id, role_id) values(1,8);
 insert into profile_role(profile_id, role_id) values(1,9);
 insert into profile_role(profile_id, role_id) values(1,10);
 insert into profile_role(profile_id, role_id) values(1,11);
 insert into profile_role(profile_id, role_id) values(1,12);
 insert into profile_role(profile_id, role_id) values(1,13);
 insert into profile_role(profile_id, role_id) values(1,14);
 insert into profile_role(profile_id, role_id) values(1,15);
 insert into profile_role(profile_id, role_id) values(1,16);
 insert into profile_role(profile_id, role_id) values(1,17);
 insert into profile_role(profile_id, role_id) values(1,18);
 insert into profile_role(profile_id, role_id) values(1,19);
 insert into profile_role(profile_id, role_id) values(1,20);
 insert into profile_role(profile_id, role_id) values(1,21);
 insert into profile_role(profile_id, role_id) values(1,22);
 insert into profile_role(profile_id, role_id) values(1,23);
 insert into profile_role(profile_id, role_id) values(1,24);
 insert into profile_role(profile_id, role_id) values(1,25);
 insert into profile_role(profile_id, role_id) values(1,26);
 insert into profile_role(profile_id, role_id) values(1,27);
 insert into profile_role(profile_id, role_id) values(1,28);
 insert into profile_role(profile_id, role_id) values(1,29);
 insert into profile_role(profile_id, role_id) values(1,30);
 insert into profile_role(profile_id, role_id) values(1,31);
 insert into profile_role(profile_id, role_id) values(1,32);
 insert into profile_role(profile_id, role_id) values(1,33);
 insert into profile_role(profile_id, role_id) values(1,34);
 insert into profile_role(profile_id, role_id) values(1,35);
 insert into profile_role(profile_id, role_id) values(1,36);
 insert into profile_role(profile_id, role_id) values(1,37);

 update role set description = lower(name);

 insert into user(email, name, password_hash, profile_id) values('admin@admin.com','admin','$2a$10$l4K/aiKHgXYVNeCoCbTRYeA0bjfBuUjlc5DVc55/hoXEXX6xUBnMy',1);
